#!/usr/bin/env bash
# set -euo pipefail

# ── Herdr Layout Save Script ──────────────────────────────────
# Captures current herdr session layout to config-$SESSION.yaml
# Overwrites on each run making backup file. Omits default values.
# ───────────────────────────────────────────────────────────────

HERDR="${HERDR_BIN_PATH:-herdr}"

# ── yq bootstrap (same as setup.sh) ──────────────────────────
if ! command -v yq &>/dev/null; then
  YQ_BIN="${HERDR_PLUGIN_ROOT:-$HOME/.config/herdr/plugins}/bin"
  [[ -d "$YQ_BIN" ]] && export PATH="$YQ_BIN:$PATH"
fi

if ! command -v yq &>/dev/null; then
  YQ_VERSION="v4.53.2"
  echo "[layout-save] yq not found — downloading yq ${YQ_VERSION}..." >&2
  case "$(uname -s)" in
    Darwin) YQ_PLATFORM="darwin_amd64";;
    Linux)  YQ_PLATFORM="linux_amd64";;
    *)      echo "[layout-save] unsupported platform" >&2; exit 1;;
  esac
  [[ "$(uname -m)" == "arm64" || "$(uname -m)" == "aarch64" ]] && YQ_PLATFORM="${YQ_PLATFORM%amd64}arm64"
  YQ_BIN="${HERDR_PLUGIN_ROOT:-$HOME/.config/herdr/plugins}/bin"
  mkdir -p "$YQ_BIN"
  curl -fsSL "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_${YQ_PLATFORM}" -o "$YQ_BIN/yq" || {
    echo "[layout-save] failed to download yq" >&2; exit 1; }
  chmod +x "$YQ_BIN/yq"
  export PATH="$YQ_BIN:$PATH"
fi

YQ=$(command -v yq)

# ── session detection ─────────────────────────────────────────
current_session() {
  if [[ "$HERDR_ENV" != 1 && -z ${HERDR_SOCKET_PATH:-} ]]; then
    # Not inside herdr
    echo "[layout-save] must be run inside herdr session!" >&2
    exit 127
  fi
  if [[ "${HERDR_SOCKET_PATH:-}" == "$HOME/.config/herdr/herdr.sock" ]]; then
    echo "default"
  else
    basename "$(dirname "${HERDR_SOCKET_PATH:-$HOME/.config/herdr/herdr.sock}")"
  fi
}

SESSION="${SESSION:-$(current_session)}"
RC=$?
test $RC -ne 0 && exit $RC
CONFIG_DIR="${HERDR_PLUGIN_CONFIG_DIR:-$HOME/.config/herdr/plugins/config/layout}"
OUTPUT="${CONFIG_DIR}/config-${SESSION}.yaml"

# Make backup of previous file
if [[ -f "$OUTPUT" ]]; then
  BACKUP_FILE=${OUTPUT}-$(date -Iseconds).backup~
  cp -p "$OUTPUT" "$BACKUP_FILE"
  echo "[layout-save] previous config file saved as: $BACKUP_FILE"
elif [[ -d "$CONFIG_DIR" ]]; then
  echo "[layout-save] there is no configuration directory for plugin, cannot continue: $CONFIG_DIR" >&2
  exit 0
fi

echo "[layout-save] session: $SESSION"
echo "[layout-save] output file: $OUTPUT"

# ── gather session state ──────────────────────────────────────
WS_JSON=$("$HERDR" --session "$SESSION" workspace list 2>/dev/null)
WORKSPACE_COUNT=$(echo "$WS_JSON" | "$YQ" -r '.result.workspaces | length // 0')

if [[ "$WORKSPACE_COUNT" -eq 0 ]]; then
  echo "[layout-save] no workspaces in session '$SESSION'" >&2
  exit 0
fi

# ── helpers ───────────────────────────────────────────────────
# Get focused workspace/tab IDs
FOCUSED_WS=$(echo "$WS_JSON" | "$YQ" -r '[.result.workspaces[] | select(.focused == true) | .workspace_id][0] // ""')
FOCUSED_TAB=$("$HERDR" --session "$SESSION" tab list 2>/dev/null |
  "$YQ" -r '[.result.tabs[] | select(.focused == true) | .tab_id][0] // ""')

# Default CWD for a workspace (from first tab's agent or cwd)
workspace_root() {
  local ws_id="$1"
  "$HERDR" --session "$SESSION" workspace get "$ws_id" 2>/dev/null |
    "$YQ" -r '.result.workspace.cwd // "~"'
}

# Default CWD for a tab
tab_cwd() {
  local tab_id="$1"
  "$HERDR" --session "$SESSION" tab get "$tab_id" 2>/dev/null |
    "$YQ" -r '.result.tab.cwd // ""'
}

# Pane foreground cwd
pane_cwd() {
  local pane_id="$1"
  "$HERDR" --session "$SESSION" pane get "$pane_id" 2>/dev/null |
    "$YQ" -r '.result.pane.foreground_cwd // ""'
}

# Detect pane command (agent or "shell")
pane_command() {
  local pane_id="$1"
  local agent
  agent=$("$HERDR" --session "$SESSION" pane get "$pane_id" 2>/dev/null |
    "$YQ" -r '.result.pane.agent // ""')
  if [[ -n "$agent" && "$agent" != "null" ]]; then
    echo "$agent"
  else
    echo ""
  fi
}

# Check if workspace belongs to mirror plugin
is_mirror_workspace() {
  local ws_id="$1"
  "$HERDR" --session "$SESSION" pane list --workspace "$ws_id" 2>/dev/null |
    "$YQ" -r '.result.panes[0].foreground_cwd // ""' 2>/dev/null |
    grep -q '.mirror-pane'
}
compact_home() {
  local path="${1:-}"
  path="${path/#$HOME/~}"
  echo "$path"
}

# ── write YAML ────────────────────────────────────────────────
{
  printf "# herdr layout for %s — session: %s\n" "$(hostname -s)" "$SESSION"
  printf "# generated by save.sh at %s\n" "$(date -Iseconds 2>/dev/null || date)"
  printf "# on %s\n\n" "$(uname -rom)"
  printf "session:\n"
  printf "  name: %s\n" "$SESSION"
  printf "# if mode is 'strict', session will be restored exactly like in\n"
  printf "# configuration file: excess workspace/tabs/planes will be closed\n"
  printf "mode: non-strict\n"
  printf "\nworkspaces:\n"

  for ((ws_i = 0; ws_i < WORKSPACE_COUNT; ws_i++)); do
    WS_ID=$(echo "$WS_JSON" | "$YQ" -r ".result.workspaces[$ws_i].workspace_id")
    WS_LABEL=$(echo "$WS_JSON" | "$YQ" -r ".result.workspaces[$ws_i].label")

    # Skip mirror plugin workspaces
    is_mirror_workspace "$WS_ID" && continue

    WS_ROOT=$(compact_home "$(workspace_root "$WS_ID")")

    printf "  - name: \"%s\"\n" "$WS_LABEL"
    printf "    root: %s\n" "$WS_ROOT"
    [[ "$WS_ID" == "$FOCUSED_WS" ]] && printf "    focus: true\n"

    TAB_JSON=$("$HERDR" --session "$SESSION" tab list --workspace "$WS_ID" 2>/dev/null)
    TAB_COUNT=$(echo "$TAB_JSON" | "$YQ" -r '.result.tabs | length // 0')
    printf "    tabs:\n"

    for ((tab_i = 0; tab_i < TAB_COUNT; tab_i++)); do
      TAB_ID=$(echo "$TAB_JSON" | "$YQ" -r ".result.tabs[$tab_i].tab_id")
      TAB_LABEL=$(echo "$TAB_JSON" | "$YQ" -r ".result.tabs[$tab_i].label")
      TAB_CWD=$(compact_home "$(tab_cwd "$TAB_ID")")

      printf "      - label: \"%s\"\n" "$TAB_LABEL"
      # Only write cwd if different from workspace root
      if [[ -n "$TAB_CWD" && "$TAB_CWD" != "null" && "$TAB_CWD" != "$WS_ROOT" ]]; then
        printf "        cwd: %s\n" "$TAB_CWD"
      fi
      [[ "$TAB_ID" == "$FOCUSED_TAB" ]] && printf "        focus: true\n"

      PANE_JSON=$("$HERDR" --session "$SESSION" pane list --workspace "$WS_ID" 2>/dev/null)
      PANE_IDS_IN_TAB=$(echo "$PANE_JSON" |
        "$YQ" -r "[.result.panes[] | select(.tab_id == \"$TAB_ID\") | .pane_id][]")

      # Get split history for this tab (from first pane's layout)
      FIRST_PANE=$(echo "$PANE_IDS_IN_TAB" | head -1)
      LAYOUT_JSON=$("$HERDR" --session "$SESSION" pane layout --pane "$FIRST_PANE" 2>/dev/null)
      SPLIT_COUNT=$(echo "$LAYOUT_JSON" | "$YQ" -r '.result.layout.splits | length // 0' 2>/dev/null)

      printf "        panes:\n"

      pane_idx=0
      while IFS= read -r PANE_ID; do
        [[ -z "$PANE_ID" ]] && continue
        PANE_CMD=$(pane_command "$PANE_ID")
        PANE_CWD=$(compact_home "$(pane_cwd "$PANE_ID")")

        printf "          - command: \"%s\"\n" "${PANE_CMD:-}"

        # Only write cwd if different from tab cwd
        if [[ -n "$PANE_CWD" && "$PANE_CWD" != "null" && "$PANE_CWD" != "$TAB_CWD" ]]; then
          printf "            cwd: %s\n" "$PANE_CWD"
        fi

        # Only write split for non-first panes
        if [[ "$pane_idx" -gt 0 ]]; then
          _split_idx=$((pane_idx - 1))
          _split_dir=$(echo "$LAYOUT_JSON" | "$YQ" -r ".result.layout.splits[$_split_idx].direction // \"down\"" 2>/dev/null)
          _split_ratio=$(echo "$LAYOUT_JSON" | "$YQ" -r ".result.layout.splits[$_split_idx].ratio // 0" 2>/dev/null)
          printf "            split: %s\n" "${_split_dir:-down}"
          # Only write ratio if not default 0.5
          if [[ -n "$_split_ratio" && "$_split_ratio" != "0" && "$_split_ratio" != "0.5" && "$_split_ratio" != "null" ]]; then
            printf "            ratio: %s\n" "$_split_ratio"
          fi
        fi

        pane_idx=$((pane_idx + 1))
      done <<< "$PANE_IDS_IN_TAB"
    done
  done
} > "$OUTPUT"

echo "[layout-save] written $(wc -l < "$OUTPUT") lines to $OUTPUT"
echo "[layout-save] done."
